# Generated by Django 6.0.4 on 2026-06-18 05:53

import crmapp.ai.xai.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiasAudit',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_bias_id, max_length=50, primary_key=True, serialize=False)),
                ('protected_attribute', models.CharField(max_length=100)),
                ('disparity_score', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('mitigation_text', models.TextField(blank=True, default='')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xai_bias_audits',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_expl_id, max_length=50, primary_key=True, serialize=False)),
                ('explainer_used', models.CharField(choices=[('SHAP', 'SHAP'), ('LIME', 'LIME'), ('TreeSHAP', 'TreeSHAP'), ('Integrated G', 'Integrated Gradients')], default='SHAP', max_length=50)),
                ('nl_explanation', models.TextField(blank=True, default='')),
                ('shap_values', models.JSONField(blank=True, default=dict)),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=200)),
                ('exported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xai_explanations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_model_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('model_type', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Healthcare', 'Healthcare'), ('HR', 'HR'), ('General', 'General')], default='General', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xai_models',
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BiasAuditGroup',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_bias_id, max_length=50, primary_key=True, serialize=False)),
                ('group_label', models.CharField(max_length=100)),
                ('rate_value', models.FloatField()),
                ('sample_size', models.IntegerField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ai_xai.biasaudit')),
            ],
            options={
                'db_table': 'xai_bias_audit_groups',
            },
        ),
        migrations.CreateModel(
            name='FeatureContribution',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_feat_id, max_length=50, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=200)),
                ('feature_value', models.CharField(blank=True, default='', max_length=200)),
                ('shap_contribution', models.FloatField()),
                ('direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20)),
                ('importance_score', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_contributions', to='ai_xai.explanation')),
            ],
            options={
                'db_table': 'xai_feature_contributions',
                'ordering': ['-importance_score'],
            },
        ),
        migrations.CreateModel(
            name='GlobalImportance',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_gimp_id, max_length=50, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=200)),
                ('avg_importance', models.FloatField()),
                ('sample_count', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_importances', to='ai_xai.mlmodel')),
            ],
            options={
                'db_table': 'xai_global_importance',
                'ordering': ['-avg_importance'],
            },
        ),
        migrations.AddField(
            model_name='biasaudit',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_audits', to='ai_xai.mlmodel'),
        ),
        migrations.CreateModel(
            name='ModelIssue',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_issue_id, max_length=50, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('shap_drift', models.FloatField(blank=True, null=True)),
                ('affected_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ai_xai.mlmodel')),
            ],
            options={
                'db_table': 'xai_model_issues',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_pred_id, max_length=50, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=100)),
                ('subject_type', models.CharField(max_length=100)),
                ('subject_name', models.CharField(blank=True, default='', max_length=200)),
                ('prediction_label', models.CharField(max_length=200)),
                ('outcome_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('warning', 'Warning')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('uncertainty_score', models.FloatField(blank=True, null=True)),
                ('raw_input', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_xai.mlmodel')),
            ],
            options={
                'db_table': 'xai_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='explanation',
            name='prediction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='ai_xai.prediction'),
        ),
        migrations.CreateModel(
            name='Counterfactual',
            fields=[
                ('id', models.CharField(default=crmapp.ai.xai.models.make_cf_id, max_length=50, primary_key=True, serialize=False)),
                ('scenario_index', models.IntegerField()),
                ('change_description', models.TextField()),
                ('impact_label', models.CharField(max_length=200)),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterfactuals', to='ai_xai.prediction')),
            ],
            options={
                'db_table': 'xai_counterfactuals',
                'ordering': ['scenario_index'],
            },
        ),
    ]
