# Generated by Django 6.0.5 on 2026-05-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity']},
        ),
    ]
