# Generated by Django 6.0.4 on 2026-06-03 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_contacts', '0002_contact_company_name_alter_contact_company_and_more'),
        ('crm_tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('is_template', models.BooleanField(default=False)),
                ('trigger_event', models.CharField(choices=[('manual', 'Manual / Bulk Send'), ('ticket_closed', 'After Ticket Closure'), ('purchase_completed', 'After Purchase'), ('onboarding_complete', 'After Onboarding'), ('demo_completed', 'After Demo')], default='manual', max_length=30)),
                ('distribution_method', models.JSONField(blank=True, default=list)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('nps', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_avatar', models.URLField(blank=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('csat_score', models.IntegerField(blank=True, null=True)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='crm_contacts.contact')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm_feedback.survey')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='crm_tickets.ticket')),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
