# Generated by Django 5.2.14 on 2026-05-12 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_snapshot', models.JSONField(default=dict)),
                ('role_at_time', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_fail', 'Login Failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('permission', 'Permission Change'), ('settings', 'Settings Change'), ('security', 'Security Event'), ('view', 'View'), ('approve', 'Approve'), ('suspend', 'Suspend'), ('password', 'Password Reset'), ('mfa', 'MFA Change'), ('api_token', 'API Token'), ('sso', 'SSO Change'), ('temp_grant', 'Temp Access Granted'), ('temp_revoke', 'Temp Access Revoked'), ('backup', 'Backup')], db_index=True, max_length=15)),
                ('module', models.CharField(choices=[('CRM', 'CRM'), ('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Analytics', 'Analytics'), ('AI', 'AI Module'), ('Settings', 'Settings'), ('Auth', 'Auth & Security'), ('System', 'System'), ('Users', 'User Management')], db_index=True, max_length=15)),
                ('entity', models.CharField(max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_logs_module_34635f_idx'), models.Index(fields=['severity', 'timestamp'], name='audit_logs_severit_549d29_idx'), models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx')],
            },
        ),
    ]
