"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from datetime import timedelta
from celery.schedules import crontab

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== SECURITY ====================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ==================== API KEYS ====================
GROQ_API_KEY   = os.getenv('GROQ_API_KEY')
TAVILY_API_KEY = os.getenv('TAVILY_API_KEY')

# ==================== TOOL KEYS ====================
# 1. Web Search — Tavily (already set above)

# 2. Email Send — Gmail SMTP
#    Get App Password: myaccount.google.com → Security → App passwords
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL  = f'NextGen CRM <{EMAIL_HOST_USER}>'

# 3. CRM Read  — no key needed (uses Django ORM directly)
# 4. CRM Write — no key needed (uses Django ORM directly)

# 5. Slack Notify — free webhook
#    Get webhook: api.slack.com/apps → Create App → Incoming Webhooks → Add New Webhook
SLACK_WEBHOOK_URL = os.getenv('SLACK_WEBHOOK_URL')

# 6. Calendar Book — Google Calendar (optional)
#    Get credentials: console.cloud.google.com → Service Account → Download JSON
#    Leave blank to save meetings as CRM tasks instead (works without this)
GOOGLE_CALENDAR_CREDENTIALS_PATH = os.getenv('GOOGLE_CALENDAR_CREDENTIALS_PATH', '')

# 7. Analytics API — no key needed (reads from your Supabase DB directly)

# ── WHATSAPP — Meta Cloud API (Free 1000/month) ───────────────────────────────
WHATSAPP_PHONE_ID     = os.getenv('WHATSAPP_PHONE_ID')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN')
WHATSAPP_VERIFY_TOKEN = os.getenv('WHATSAPP_VERIFY_TOKEN', 'nextgencrm_verify_2024')

EMAIL_TO_LEAD_WEBHOOK_URL = os.getenv(
    'EMAIL_TO_LEAD_WEBHOOK_URL',
    'http://localhost:8000/api/automation/workflows/webhooks/2b69987f90aa45fdb0408cf5d2037a0e/'
)
AUTOMATION_SYSTEM_USER_ID = int(os.getenv('AUTOMATION_SYSTEM_USER_ID', 25))  # superadmin — owns leads created by AI agents/workflows


# ==================== CELERY ====================
CELERY_BROKER_URL        = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND    = "django-db"
CELERY_ACCEPT_CONTENT    = ["json"]
CELERY_TASK_SERIALIZER   = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE          = "UTC"
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_TASK_ALWAYS_EAGER = False
CELERY_WORKER_POOL = "solo"

CELERY_BEAT_SCHEDULE = {
    "check-ready-tasks-every-minute": {
        "task":     "agents.check_ready_tasks",
        "schedule": 60.0,
    },
    "promote-scheduled-tasks-every-minute": {
        "task":     "agents.promote_scheduled_tasks",
        "schedule": 60.0,
    },
    "poll-gmail-inboxes": {
        "task":     "crmapp.ai.emotion_detection.tasks.poll_all_gmail_inboxes",
        "schedule": 600.0,
    },
    "process-recurring-followups": {
        "task":     "crmapp.crm.followups.tasks.process_recurring_followups",
        "schedule": 3600.0,   # checks every hour
    },
}


# ==================== INSTALLED APPS ====================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'rest_framework.authtoken',
    'django_celery_results',

    # Your apps — ORDER MATTERS: core before tasks before agents
    'crmapp',
    'crmapp.agentic',
    'crmapp.agentic.core',
    'crmapp.agentic.tasks',
    'crmapp.agentic.agents',

    'crmapp.finance.coa',
    'crmapp.finance.aps',
    'crmapp.finance.cashbank',
    'crmapp.finance.assets',
    'crmapp.finance.payroll',
    'crmapp.finance.expense',
    'crmapp.finance.invoicear',
    'crmapp.finance.ledger',

    'crmapp.system.usermanage',
    'crmapp.system.roles',
    'crmapp.system.auth_security',
    'crmapp.system.audit',
    'crmapp.system.settings_config',

    'crmapp.crm.leads',
    'crmapp.crm.companies',
    'crmapp.crm.contacts',
    'crmapp.crm.pipeline',
    'crmapp.crm.deals',
    'crmapp.crm.activities',
    'crmapp.crm.followups',
    'crmapp.crm.contracts',
    'crmapp.crm.tickets',
    'crmapp.crm.feedbacks',

    'crmapp.agentic.analytics',
    'crmapp.analytics',

    'crmapp.ai.emotion_detection',
    'crmapp.ai.xai',
    'crmapp.ai.recommendation',

    'crmapp.automation.workflows',
    'crmapp.dashboards',
]

# ==================== MIDDLEWARE ====================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ==================== DATABASE ====================
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE':  'django.db.backends.postgresql',
        'NAME':    os.getenv('DB_NAME', 'postgres'),
        'USER':    os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST':    os.getenv('DB_HOST'),
        'PORT':    os.getenv('DB_PORT', '5432'),
        'OPTIONS': {'sslmode': 'require'},
    }
}

# ==================== PASSWORD VALIDATION ====================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==================== INTERNATIONALISATION ====================
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True

# ==================== STATIC & MEDIA ====================
STATIC_URL  = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL   = '/media/'
MEDIA_ROOT  = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CORS ====================
# CORS Configuration - Allow React frontend to access Django API
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173'
).split(',')

# For development only — never True in production
CORS_ALLOW_ALL_ORIGINS  = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'
CORS_ALLOW_CREDENTIALS  = True

CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
]
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

# ==================== REST FRAMEWORK ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==================== CSRF ====================
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173'
).split(',')
CSRF_COOKIE_SECURE   = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token
CSRF_USE_SESSIONS    = False
CSRF_COOKIE_SAMESITE = 'Lax'

# ==================== SESSION ====================
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE   = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE      = 1209600

# ==================== LOGGING ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
        'file':    {'class': 'logging.FileHandler', 'filename': BASE_DIR / 'debug.log', 'formatter': 'verbose'},
    },
    'root': {'handlers': ['console', 'file'], 'level': 'INFO'},
    'loggers': {
        'django':               {'handlers': ['console', 'file'], 'level': 'INFO',  'propagate': False},
        'crmapp':               {'handlers': ['console', 'file'], 'level': 'INFO',  'propagate': False},
        'crmapp.agentic.tasks': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': False},
        'celery':               {'handlers': ['console', 'file'], 'level': 'INFO',  'propagate': False},
    },
}

HUGGINGFACE_API_TOKEN = os.getenv('HUGGINGFACE_API_TOKEN')

GOOGLE_CLIENT_ID     = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI  = os.getenv(
    'GOOGLE_REDIRECT_URI',
    'http://localhost:8000/api/ai/emotion_detection/gmail/callback/'
)

# ==================== GROQ ====================
GROQ_API_URL     = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL       = "llama-3.3-70b-versatile"
GROQ_MAX_TOKENS  = 2000
GROQ_TEMPERATURE = 0.3
GROQ_TIMEOUT     = 30

# ==================== TASK ENGINE ====================
TASK_EXECUTION_TIMEOUT       = 300
TASK_MAX_RETRIES             = 3
TASK_RETRY_DELAY             = 60
GOAL_PARSER_MAX_TASKS        = 10
GOAL_PARSER_DEFAULT_PRIORITY = 'medium'