# Generated by Django 6.0.4 on 2026-06-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_analytics', '0001_initial'),
        ('agentic_core', '0002_resource_current_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentkpi',
            name='invert',
            field=models.BooleanField(default=False, help_text='True when lower is better (e.g. response time)'),
        ),
        migrations.AlterField(
            model_name='agentkpi',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='NULL = fleet-wide KPI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='agentic_core.resource'),
        ),
        migrations.AlterField(
            model_name='agentweeklytask',
            name='week_end',
            field=models.DateField(help_text='The Sunday (last day) of this 7-day window'),
        ),
        migrations.AlterField(
            model_name='hitlfeedback',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitl_feedback', to='agentic_core.resource'),
        ),
    ]
