# Generated by Django 6.0.4 on 2026-06-02 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_companies', '0001_initial'),
        ('crm_contacts', '0002_contact_company_name_alter_contact_company_and_more'),
        ('crm_leads', '0001_initial'),
        ('crm_pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('probability', models.IntegerField(default=50)),
                ('stage', models.CharField(choices=[('new', 'New'), ('prospect', 'Prospect'), ('proposal', 'Proposal'), ('won', 'Won')], default='new', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('assignee_avatar', models.URLField(blank=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_companies.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_leads.lead')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_pipeline.pipeline')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
