# Generated by Django 5.2.14 on 2026-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('linked_module', models.CharField(blank=True, choices=[('Cash & Bank', 'Cash & Bank'), ('AR', 'AR'), ('AP', 'AP'), ('Payroll', 'Payroll'), ('Assets', 'Assets')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Activated', 'Activated'), ('Deactivated', 'Deactivated')], max_length=20)),
                ('field', models.CharField(blank=True, default='—', max_length=100)),
                ('old_value', models.CharField(blank=True, default='—', max_length=255)),
                ('new_value', models.CharField(blank=True, default='—', max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
