# Generated by Django 6.0.4 on 2026-06-26 00:31

import crmapp.agentic.tasks.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_tmpl_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal_text', models.TextField()),
                ('template_tasks', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'goal_templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_perf_id, max_length=50, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_failed', models.IntegerField(default=0)),
                ('avg_execution_ms', models.IntegerField(default=0)),
                ('on_time_percentage', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'monthly_performance',
                'ordering': ['year', 'month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_task_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('idle', 'Idle'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(choices=[('Sales', 'Sales'), ('Finance', 'Finance'), ('Support', 'Support'), ('CRM', 'CRM'), ('Marketing', 'Marketing'), ('Analytics', 'Analytics'), ('HR', 'HR')], max_length=50)),
                ('schedule', models.CharField(default='On trigger', max_length=100)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parallel_execution', models.BooleanField(default=False)),
                ('exec_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('estimated_steps', models.IntegerField(default=1)),
                ('actual_duration_ms', models.IntegerField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='agentic_tasks.task')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BottleneckAlert',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_alert_id, max_length=50, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('issue', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('impact', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentic_tasks.task')),
            ],
            options={
                'db_table': 'bottleneck_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_dep_id, max_length=50, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel'), ('conditional', 'Conditional')], default='sequential', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='agentic_tasks.task')),
                ('to_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='agentic_tasks.task')),
            ],
            options={
                'db_table': 'task_dependencies',
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionHistory',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_hist_id, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(choices=[('Sales', 'Sales'), ('Finance', 'Finance'), ('Support', 'Support'), ('CRM', 'CRM'), ('Marketing', 'Marketing'), ('Analytics', 'Analytics'), ('HR', 'HR')], max_length=50)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='agentic_tasks.task')),
            ],
            options={
                'db_table': 'task_execution_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.tasks.models.make_goal_id, max_length=50, primary_key=True, serialize=False)),
                ('user_input', models.TextField()),
                ('parsed_goal', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('parsing', 'Parsing'), ('parsed', 'Parsed'), ('building', 'Building Tasks'), ('ready', 'Ready'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='parsing', max_length=20)),
                ('llm_response', models.JSONField(blank=True, default=dict)),
                ('structured_tasks', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parsing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='goals_status_6bb941_idx'), models.Index(fields=['created_at'], name='goals_created_f3653a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['dept'], name='tasks_dept_16732a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_created_db4e37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('from_task', 'to_task')},
        ),
        migrations.AddIndex(
            model_name='taskexecutionhistory',
            index=models.Index(fields=['task', 'started_at'], name='task_execut_task_id_90a28f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionhistory',
            index=models.Index(fields=['status'], name='task_execut_status_cb0410_idx'),
        ),
    ]
