# Generated by Django 5.2.14 on 2026-05-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('lockout_duration', models.PositiveIntegerField(default=15)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('max_sessions', models.PositiveSmallIntegerField(default=3)),
                ('captcha_enabled', models.BooleanField(default=True)),
                ('ip_restriction', models.BooleanField(default=False)),
                ('passwordless_enabled', models.BooleanField(default=False)),
                ('adaptive_auth', models.BooleanField(default=True)),
                ('require_mfa', models.BooleanField(default=False)),
                ('remember_me', models.BooleanField(default=True)),
                ('remember_me_days', models.PositiveSmallIntegerField(default=7)),
                ('access_token_expiry', models.PositiveIntegerField(default=30)),
                ('refresh_token_expiry', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_policy',
            },
        ),
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon_label', models.CharField(default='?', max_length=10)),
                ('color_hex', models.CharField(default='#3a9aab', max_length=9)),
                ('protocol', models.CharField(choices=[('oauth2', 'OAuth 2.0'), ('saml2', 'SAML 2.0')], max_length=8)),
                ('client_id', models.CharField(blank=True, max_length=300)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('metadata_url', models.URLField(blank=True)),
                ('redirect_uri', models.URLField(blank=True)),
                ('tenant_domain', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('user_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sso_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('token_prefix', models.CharField(max_length=30)),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring Soon'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_ips',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.CharField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked'), ('suspicious', 'Suspicious')], db_index=True, max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('mfa_used', models.BooleanField(default=False)),
                ('session_duration', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MFAUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('totp', 'Authenticator App'), ('sms', 'SMS OTP'), ('email', 'Email OTP'), ('bio', 'Biometric')], default='totp', max_length=10)),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('backup_codes', models.JSONField(default=list)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_users',
            },
        ),
    ]
