# Generated by Django 6.0.4 on 2026-07-05 10:55

import crmapp.automation.workflows.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._wf_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowedge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='crm_workflows.workflownode'),
        ),
        migrations.AlterField(
            model_name='workflowedge',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._ed_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowedge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='crm_workflows.workflownode'),
        ),
        migrations.AlterField(
            model_name='workflowedge',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='crm_workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_executions', to='crm_workflows.workflownode'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._ex_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='crm_workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowexecutionstep',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm_workflows.workflowexecution'),
        ),
        migrations.AlterField(
            model_name='workflowexecutionstep',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._st_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowexecutionstep',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm_workflows.workflownode'),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._nd_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='crm_workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._ver_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crm_workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowwebhook',
            name='id',
            field=models.CharField(default=crmapp.automation.workflows.models._whk_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowwebhook',
            name='secret',
            field=models.CharField(default=crmapp.automation.workflows.models.WorkflowWebhook._whk_secret, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowwebhook',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='crm_workflows.workflow'),
        ),
    ]
