# Generated by Django 6.0.4 on 2026-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_workflows', '0002_alter_workflow_id_alter_workflowedge_from_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowwebhook',
            name='trigger_on_lead_created',
            field=models.BooleanField(default=False, help_text='If enabled, this workflow fires automatically whenever a new Lead is created.'),
        ),
    ]
