# Generated by Django 6.0.4 on 2026-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_workflows', '0003_workflowwebhook_trigger_on_lead_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowwebhook',
            name='trigger_on_lead_created',
        ),
        migrations.AddField(
            model_name='workflow',
            name='trigger_on_lead_created',
            field=models.BooleanField(default=False, help_text='If enabled, this workflow fires automatically whenever a new Lead is created.'),
        ),
    ]
