# Generated by Django 6.0.4 on 2026-06-08 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], max_length=20)),
                ('threshold', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('action', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('slack', 'Slack'), ('email', 'Email'), ('in_app', 'In-App'), ('crm', 'CRM')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['emotion', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='EmotionDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_body_snippet', models.TextField(blank=True)),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], max_length=20)),
                ('intensity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('confidence', models.FloatField()),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_fired', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotion Detection',
                'verbose_name_plural': 'Emotion Detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('actioned', 'Actioned'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emotion_detection.alertrule')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='emotion_detection.emotiondetection')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_address', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_interval', models.IntegerField(default=10)),
                ('sender_filter', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Connection',
                'verbose_name_plural': 'Gmail Connections',
            },
        ),
        migrations.AddIndex(
            model_name='emotiondetection',
            index=models.Index(fields=['user', 'detected_at'], name='emotion_det_user_id_044ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='emotiondetection',
            index=models.Index(fields=['user', 'emotion'], name='emotion_det_user_id_ce09bd_idx'),
        ),
        migrations.AddIndex(
            model_name='emotiondetection',
            index=models.Index(fields=['customer_email'], name='emotion_det_custome_64015c_idx'),
        ),
    ]
