# Generated by Django 6.0.4 on 2026-06-25 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmailconnection',
            options={'ordering': ['-connected_at'], 'verbose_name': 'Gmail Connection', 'verbose_name_plural': 'Gmail Connections'},
        ),
        migrations.AddField(
            model_name='emotiondetection',
            name='gmail_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='emotion_detection.gmailconnection'),
        ),
        migrations.AlterField(
            model_name='gmailconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gmailconnection',
            unique_together={('user', 'gmail_address')},
        ),
    ]
