# Generated by Django 6.0.4 on 2026-06-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_activities', '0001_initial'),
        ('crm_deals', '0001_initial'),
        ('crm_leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activitY_records', to='crm_deals.deal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='crm_leads.lead'),
        ),
    ]
