# Generated by Django 6.0.4 on 2026-05-25 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('no_of_deals', models.IntegerField(default=0)),
                ('stage', models.CharField(choices=[('Won', 'Won'), ('In Pipeline', 'In Pipeline'), ('Conversation', 'Conversation'), ('Follow Up', 'Follow Up'), ('Schedule Service', 'Schedule Service'), ('Lost', 'Lost')], default='In Pipeline', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('color', models.CharField(blank=True, default='#296571', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipelines',
                'ordering': ['-created_at'],
            },
        ),
    ]
