# Generated by Django 5.2.14 on 2026-05-08 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave')], max_length=10)),
                ('check_in', models.CharField(blank=True, max_length=20, null=True)),
                ('check_out', models.CharField(blank=True, max_length=20, null=True)),
                ('break_time', models.CharField(blank=True, max_length=20, null=True)),
                ('late', models.CharField(blank=True, max_length=20, null=True)),
                ('desk', models.CharField(blank=True, max_length=20, null=True)),
                ('overtime', models.CharField(blank=True, max_length=20, null=True)),
                ('production_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('applied_role', models.CharField(max_length=100)),
                ('applied_date', models.DateField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Scheduled', 'Scheduled'), ('Interviewed', 'Interviewed'), ('Offered', 'Offered'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='candidates/avatars/')),
                ('resume_url', models.FileField(blank=True, null=True, upload_to='candidates/resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='crmFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('message_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('employees', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('employees', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Remote', 'Remote')], default='Full-Time', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('filled', 'Filled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('applicants', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Medical Leave', 'Medical Leave'), ('Casual Leave', 'Casual Leave'), ('Other', 'Other')], max_length=50)),
                ('badge', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('approved_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_by_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average')], default='Good', max_length=20)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=2, null=True)),
                ('promotion_date', models.DateField()),
                ('color', models.CharField(blank=True, default='#8b5cf6', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('Career Change', 'Career Change'), ('Entrepreneurial Pursuits', 'Entrepreneurial Pursuits'), ('Relocation', 'Relocation'), ('Health Reasons', 'Health Reasons'), ('Personal Development', 'Personal Development'), ('Better Opportunity', 'Better Opportunity'), ('Family Reasons', 'Family Reasons')], max_length=100)),
                ('notice_date', models.DateField()),
                ('resignation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-resignation_date'],
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=2, null=True)),
                ('termination_type', models.CharField(choices=[('Retirement', 'Retirement'), ('Insubordination', 'Insubordination'), ('Layoff', 'Layoff'), ('Breach of Contract', 'Breach of Contract'), ('Lack of Skills', 'Lack of Skills'), ('Voluntary Resignation', 'Voluntary Resignation')], max_length=50)),
                ('notice_date', models.DateField()),
                ('reason', models.TextField()),
                ('resignation_date', models.DateField()),
                ('color', models.CharField(blank=True, default='#8b5cf6', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-resignation_date'],
            },
        ),
    ]
