# Generated by Django 6.0.5 on 2026-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
