# Generated by Django 6.0.5 on 2026-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_alter_crmfile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termination',
            options={'ordering': ['-termination_date']},
        ),
        migrations.AddField(
            model_name='termination',
            name='termination_date',
             field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='termination',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_time',
            field=models.IntegerField(blank=True, help_text='Break duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='desk',
            field=models.IntegerField(blank=True, help_text='Desk time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late',
            field=models.IntegerField(blank=True, help_text='Late duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.IntegerField(blank=True, help_text='Overtime in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='production_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Production hours as decimal e.g. 8.2', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by_avatar',
            field=models.CharField(blank=True, default='https://api.dicebear.com/7.x/avataaars/svg?seed=pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by_name',
            field=models.CharField(blank=True, default='Pending Approval', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by_role',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
    ]
