# Generated by Django 6.0.5 on 2026-05-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_alter_termination_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termination',
            name='resignation_date',
        ),
    ]
