# Generated by Django 6.0.5 on 2026-06-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_employee_address_employee_avatar_employee_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationReinstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reinstated_date', models.DateField()),
                ('court_case_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('salary_paid', models.BooleanField(default=False)),
                ('salary_paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('termination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinstatements', to='crmapp.termination')),
            ],
            options={
                'ordering': ['-reinstated_date'],
            },
        ),
    ]
