# Generated by Django 5.2.14 on 2026-05-12 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.EmailField(default='', max_length=254)),
                ('smtp_password', models.CharField(blank=True, max_length=300)),
                ('encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=4)),
                ('sender_name', models.CharField(default='NextCRM', max_length=100)),
                ('sender_email', models.EmailField(default='', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_configs',
            },
        ),
        migrations.CreateModel(
            name='IntegrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_label', models.CharField(default='?', max_length=10)),
                ('color_hex', models.CharField(default='#3a9aab', max_length=9)),
                ('key_encrypted', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=10)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integration_keys',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notif', models.BooleanField(default=True)),
                ('sms_notif', models.BooleanField(default=False)),
                ('push_notif', models.BooleanField(default=True)),
                ('in_app_notif', models.BooleanField(default=True)),
                ('new_lead', models.BooleanField(default=True)),
                ('task_assigned', models.BooleanField(default=True)),
                ('deal_closed', models.BooleanField(default=True)),
                ('invoice_due', models.BooleanField(default=True)),
                ('invoice_paid', models.BooleanField(default=True)),
                ('login_alert', models.BooleanField(default=True)),
                ('new_contact', models.BooleanField(default=False)),
                ('report_ready', models.BooleanField(default=True)),
                ('system_error', models.BooleanField(default=True)),
                ('maintenance', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=True)),
                ('monthly_report', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('size_display', models.CharField(max_length=20)),
                ('backup_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=8)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('running', 'Running'), ('failed', 'Failed')], default='running', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='NextCRM', max_length=100)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=60)),
                ('language', models.CharField(default='en', max_length=20)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('fiscal_year', models.CharField(default='Jan-Dec', max_length=20)),
                ('primary_color', models.CharField(default='#3a9aab', max_length=9)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=8)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('favicon_url', models.CharField(blank=True, max_length=300)),
                ('module_config', models.JSONField(default=dict)),
                ('feature_flags', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
