"""
crmapp/ai/recommendation/models.py

Tables:
  1. UserProfile        — computed profile per Lead/Contact (score, churn, LTV, etc.)
  2. RecommendationItem — a single actionable recommendation for a subject
  3. FeedbackEvent      — click / purchase / ignore signals for continuous learning
  4. ABTest             — experiment registry
  5. ABTestAssignment   — which variant a subject was shown
  6. ChannelPerformance — daily snapshot per delivery channel
  7. ModelPerformance   — monthly CTR / conv / revenue / precision per rec model
  8. ProactiveAlert     — fired when XAI or Emotion signals cross a threshold
"""

import uuid
from django.db import models
from django.conf import settings


# ── ID helpers ────────────────────────────────────────────────────────────────

def _uid(prefix):
    return f"{prefix}-{uuid.uuid4().hex[:8]}"

def make_profile_id():    return _uid("prof")
def make_rec_id():        return _uid("rec")
def make_feedback_id():   return _uid("fb")
def make_abtest_id():     return _uid("ab")
def make_assign_id():     return _uid("asgn")
def make_channel_id():    return _uid("ch")
def make_mperf_id():      return _uid("mp")
def make_alert_id():      return _uid("pa")


# ── 1. UserProfile ────────────────────────────────────────────────────────────

class UserProfile(models.Model):
    """
    One row per CRM subject (Lead or Contact).
    Built nightly from Lead / Deal / EmotionDetection / XAI Prediction tables.
    Also rebuilt on-demand when a ProactiveAlert fires.
    """

    SUBJECT_TYPE_CHOICES = [
        ("lead",    "Lead"),
        ("contact", "Contact"),
    ]

    SEGMENT_CHOICES = [
        ("high_value", "High-Value"),
        ("loyal",      "Loyal"),
        ("at_risk",    "At-Risk"),
        ("new",        "New"),
        ("occasional", "Occasional"),
    ]

    CHANNEL_CHOICES = [
        ("web",    "Web"),
        ("mobile", "Mobile"),
        ("email",  "Email"),
        ("push",   "Push"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_profile_id)

    # ── Subject reference (points at Lead or Contact PK) ─────────────────────
    subject_type    = models.CharField(max_length=20, choices=SUBJECT_TYPE_CHOICES)
    subject_id      = models.CharField(max_length=100)   # str(Lead.id) or str(Contact.id)
    subject_name    = models.CharField(max_length=255, blank=True, default="")
    subject_email   = models.EmailField(blank=True, default="")

    # ── Computed scores ───────────────────────────────────────────────────────
    engagement_score  = models.FloatField(default=0.0)   # 0–100
    churn_risk_score  = models.FloatField(default=0.0)   # 0–100  (higher = more at risk)
    ltv_estimate      = models.FloatField(default=0.0)   # estimated lifetime value in currency units
    purchase_count    = models.IntegerField(default=0)   # number of closed-won deals / activities

    # ── Classification ────────────────────────────────────────────────────────
    segment           = models.CharField(max_length=20, choices=SEGMENT_CHOICES, default="new")
    top_category      = models.CharField(max_length=100, blank=True, default="")  # top deal tag / source
    preferred_channel = models.CharField(max_length=20, choices=CHANNEL_CHOICES, default="email")

    # ── Signal cache (from other AI systems) ─────────────────────────────────
    last_emotion        = models.CharField(max_length=20, blank=True, default="")   # from EmotionDetection
    last_emotion_score  = models.FloatField(null=True, blank=True)
    xai_conversion_prob = models.FloatField(null=True, blank=True)  # from XAI Lead Conversion Predictor
    xai_deal_win_prob   = models.FloatField(null=True, blank=True)  # from XAI Deal Win Predictor

    # ── Meta ──────────────────────────────────────────────────────────────────
    last_computed_at  = models.DateTimeField(auto_now=True)
    created_at        = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table        = "rec_user_profiles"
        unique_together = [("subject_type", "subject_id")]
        ordering        = ["-engagement_score"]
        indexes         = [
            models.Index(fields=["subject_type", "subject_id"]),
            models.Index(fields=["segment"]),
            models.Index(fields=["churn_risk_score"]),
        ]

    def __str__(self):
        return f"{self.subject_name} [{self.segment}] score={self.engagement_score:.0f}"


# ── 2. RecommendationItem ─────────────────────────────────────────────────────

class RecommendationItem(models.Model):
    """
    One actionable recommendation for one subject.
    Generated by the scoring engine, delivered via a channel.
    """

    TYPE_CHOICES = [
        ("upsell",     "Upsell"),
        ("cross_sell", "Cross-Sell"),
        ("retention",  "Retention"),
        ("re_engage",  "Re-Engage"),
        ("top_n",      "Top-N"),
        ("next_action","Next Best Action"),
    ]

    MODEL_CHOICES = [
        ("hybrid",      "Hybrid"),
        ("collab",      "Collaborative Filtering"),
        ("content",     "Content-Based"),
        ("context",     "Context-Aware"),
        ("proactive",   "Proactive (Signal-Driven)"),
    ]

    STATUS_CHOICES = [
        ("pending",   "Pending"),
        ("delivered", "Delivered"),
        ("clicked",   "Clicked"),
        ("converted", "Converted"),
        ("dismissed", "Dismissed"),
        ("expired",   "Expired"),
    ]

    CHANNEL_CHOICES = [
        ("web",    "Web"),
        ("mobile", "Mobile"),
        ("email",  "Email"),
        ("push",   "Push"),
        ("in_app", "In-App"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_rec_id)
    profile         = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        related_name="recommendations",
    )

    # ── What to recommend ────────────────────────────────────────────────────
    rec_type        = models.CharField(max_length=20, choices=TYPE_CHOICES)
    title           = models.CharField(max_length=500)        # e.g. "Follow up with Ali Hassan"
    description     = models.TextField(blank=True, default="")
    action_url      = models.CharField(max_length=500, blank=True, default="")  # deep link

    # ── Scoring ───────────────────────────────────────────────────────────────
    relevance_score   = models.FloatField(default=0.0)   # 0–100 final ranked score
    revenue_impact    = models.FloatField(default=0.0)   # expected revenue contribution
    confidence        = models.FloatField(default=0.0)   # 0–1

    # ── Model & channel ───────────────────────────────────────────────────────
    model_used      = models.CharField(max_length=20, choices=MODEL_CHOICES, default="hybrid")
    channel         = models.CharField(max_length=20, choices=CHANNEL_CHOICES, default="email")
    status          = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

    # ── Explainability ────────────────────────────────────────────────────────
    # List of human-readable reason strings shown to the sales rep
    reasons         = models.JSONField(default=list, blank=True)
    # Signals that triggered this recommendation (e.g. {"emotion": "angry", "churn_risk": 0.72})
    trigger_signals = models.JSONField(default=dict, blank=True)

    # ── Proactive flag ────────────────────────────────────────────────────────
    is_proactive    = models.BooleanField(default=False)   # True = fired by signal, not scheduled
    proactive_alert = models.ForeignKey(
        "ProactiveAlert",
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="recommendations",
    )

    # ── Meta ──────────────────────────────────────────────────────────────────
    delivered_at    = models.DateTimeField(null=True, blank=True)
    expires_at      = models.DateTimeField(null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "rec_recommendations"
        ordering = ["-relevance_score", "-created_at"]
        indexes  = [
            models.Index(fields=["profile", "status"]),
            models.Index(fields=["status", "created_at"]),
            models.Index(fields=["is_proactive"]),
        ]

    def __str__(self):
        return f"[{self.rec_type}] {self.title} → {self.profile.subject_name} ({self.relevance_score:.0f})"


# ── 3. FeedbackEvent ──────────────────────────────────────────────────────────

class FeedbackEvent(models.Model):
    """
    Records every interaction with a recommendation.
    Explicit signals (converted, rated) carry higher weight than implicit (clicked).
    Accumulated signals trigger model retraining via Celery.
    """

    ACTION_CHOICES = [
        ("clicked",       "Clicked"),
        ("converted",     "Converted / Purchased"),
        ("ignored",       "Ignored"),
        ("dismissed",     "Dismissed"),
        ("rated_up",      "Rated Up"),
        ("rated_down",    "Rated Down"),
        ("unsubscribed",  "Unsubscribed"),
        ("opened",        "Opened"),
    ]

    SIGNAL_CHOICES = [
        ("explicit", "Explicit"),
        ("implicit", "Implicit"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_feedback_id)
    recommendation  = models.ForeignKey(
        RecommendationItem,
        on_delete=models.CASCADE,
        related_name="feedback_events",
    )
    profile         = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        related_name="feedback_events",
    )

    action          = models.CharField(max_length=20, choices=ACTION_CHOICES)
    signal_type     = models.CharField(max_length=10, choices=SIGNAL_CHOICES)
    weight          = models.FloatField(default=0.0)    # 0.0–1.0 (1.0 = converted/rated)

    # Optional: revenue realised if action=converted
    revenue_realised = models.FloatField(default=0.0)

    recorded_at     = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "rec_feedback_events"
        ordering = ["-recorded_at"]
        indexes  = [
            models.Index(fields=["profile", "recorded_at"]),
            models.Index(fields=["action"]),
        ]

    def __str__(self):
        return f"{self.profile.subject_name} → {self.action} on '{self.recommendation.title}'"


# ── 4. ABTest ─────────────────────────────────────────────────────────────────

class ABTest(models.Model):
    """
    Experiment registry. Each test has two variants (control / treatment).
    Statistical confidence is computed automatically when enough outcomes accumulate.
    """

    STATUS_CHOICES = [
        ("draft",     "Draft"),
        ("running",   "Running"),
        ("completed", "Completed"),
        ("paused",    "Paused"),
    ]

    METRIC_CHOICES = [
        ("ctr",      "Click-Through Rate"),
        ("conv",     "Conversion Rate"),
        ("revenue",  "Revenue"),
        ("trust",    "Trust Score"),
        ("open_rate","Open Rate"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_abtest_id)
    name            = models.CharField(max_length=300)
    description     = models.TextField(blank=True, default="")

    # What we're comparing
    control_label   = models.CharField(max_length=100, default="Control")
    treatment_label = models.CharField(max_length=100, default="Treatment")

    primary_metric  = models.CharField(max_length=20, choices=METRIC_CHOICES, default="ctr")
    status          = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")

    # Results (computed by services.compute_ab_results)
    winner          = models.CharField(max_length=100, blank=True, default="")
    lift            = models.FloatField(null=True, blank=True)        # % improvement
    confidence      = models.FloatField(null=True, blank=True)        # 0–100
    sample_size     = models.IntegerField(default=0)

    # Timing
    started_at      = models.DateTimeField(null=True, blank=True)
    ended_at        = models.DateTimeField(null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "rec_ab_tests"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.name} [{self.status}]"

    @property
    def duration_days(self):
        if self.started_at and self.ended_at:
            return (self.ended_at - self.started_at).days
        return None


# ── 5. ABTestAssignment ───────────────────────────────────────────────────────

class ABTestAssignment(models.Model):
    """
    Tracks which variant (control/treatment) each profile was shown.
    Outcome is recorded when a FeedbackEvent fires for the linked recommendation.
    """

    VARIANT_CHOICES = [
        ("control",   "Control"),
        ("treatment", "Treatment"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_assign_id)
    test            = models.ForeignKey(ABTest, on_delete=models.CASCADE, related_name="assignments")
    profile         = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="ab_assignments")
    recommendation  = models.ForeignKey(RecommendationItem, on_delete=models.SET_NULL, null=True, blank=True, related_name="ab_assignments")

    variant         = models.CharField(max_length=20, choices=VARIANT_CHOICES)
    converted       = models.BooleanField(default=False)
    metric_value    = models.FloatField(null=True, blank=True)   # e.g. revenue amount

    assigned_at     = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table        = "rec_ab_test_assignments"
        unique_together = [("test", "profile")]
        ordering        = ["-assigned_at"]

    def __str__(self):
        return f"{self.test.name} → {self.profile.subject_name} ({self.variant})"


# ── 6. ChannelPerformance ─────────────────────────────────────────────────────

class ChannelPerformance(models.Model):
    """
    Daily snapshot of delivery volume, CTR, and conversion per channel.
    Written by the nightly Celery beat task.
    """

    CHANNEL_CHOICES = [
        ("web",    "Web"),
        ("mobile", "Mobile"),
        ("email",  "Email"),
        ("push",   "Push"),
        ("in_app", "In-App"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_channel_id)
    channel         = models.CharField(max_length=20, choices=CHANNEL_CHOICES)
    date            = models.DateField()

    recs_delivered  = models.IntegerField(default=0)
    recs_clicked    = models.IntegerField(default=0)
    recs_converted  = models.IntegerField(default=0)

    ctr             = models.FloatField(default=0.0)   # recs_clicked / recs_delivered * 100
    conv_rate       = models.FloatField(default=0.0)   # recs_converted / recs_delivered * 100
    revenue         = models.FloatField(default=0.0)   # sum of revenue_realised from FeedbackEvent

    class Meta:
        db_table        = "rec_channel_performance"
        unique_together = [("channel", "date")]
        ordering        = ["-date", "channel"]

    def __str__(self):
        return f"{self.channel} on {self.date}: CTR={self.ctr:.1f}%"


# ── 7. ModelPerformance ───────────────────────────────────────────────────────

class ModelPerformance(models.Model):
    """
    Monthly performance per recommendation model (hybrid / collab / content / context).
    Used to populate the Performance tab trend chart.
    """

    MODEL_CHOICES = [
        ("hybrid",   "Hybrid"),
        ("collab",   "Collaborative Filtering"),
        ("content",  "Content-Based"),
        ("context",  "Context-Aware"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_mperf_id)
    model_name      = models.CharField(max_length=20, choices=MODEL_CHOICES)
    year            = models.IntegerField()
    month           = models.IntegerField()   # 1–12

    recs_total      = models.IntegerField(default=0)
    ctr             = models.FloatField(default=0.0)
    conv_rate       = models.FloatField(default=0.0)
    revenue         = models.FloatField(default=0.0)
    precision       = models.FloatField(default=0.0)   # model accuracy %

    computed_at     = models.DateTimeField(auto_now=True)

    class Meta:
        db_table        = "rec_model_performance"
        unique_together = [("model_name", "year", "month")]
        ordering        = ["-year", "-month", "model_name"]

    def __str__(self):
        return f"{self.model_name} {self.year}/{self.month:02d}: CTR={self.ctr:.1f}%"


# ── 8. ProactiveAlert ─────────────────────────────────────────────────────────

class ProactiveAlert(models.Model):
    """
    Fired when cross-system signals breach a threshold.
    Each alert immediately triggers RecommendationItem generation.

    Signal sources:
      - XAI: lead conversion probability drops / deal win probability low
      - EmotionDetection: angry / fearful email detected for a known contact
      - CRM: deal stalled, lead not contacted, contract expiring
    """

    TRIGGER_CHOICES = [
        ("emotion_angry",       "Angry Email Detected"),
        ("emotion_fearful",     "Fearful Email Detected"),
        ("churn_risk_high",     "High Churn Risk (XAI)"),
        ("conversion_drop",     "Conversion Probability Dropped"),
        ("deal_stalled",        "Deal Stalled in Stage"),
        ("lead_no_contact",     "Lead Not Contacted"),
        ("contract_expiring",   "Contract Expiring Soon"),
        ("similar_lead_closed", "Similar Lead Just Closed"),
    ]

    SEVERITY_CHOICES = [
        ("low",      "Low"),
        ("medium",   "Medium"),
        ("high",     "High"),
        ("critical", "Critical"),
    ]

    id              = models.CharField(max_length=60, primary_key=True, default=make_alert_id)
    profile         = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        related_name="proactive_alerts",
    )

    trigger_type    = models.CharField(max_length=30, choices=TRIGGER_CHOICES)
    severity        = models.CharField(max_length=10, choices=SEVERITY_CHOICES, default="medium")

    # Raw signal data that caused this alert
    signal_data     = models.JSONField(default=dict, blank=True)
    # e.g. {"emotion": "angry", "confidence": 0.91, "email_subject": "Still waiting..."}
    # or   {"churn_risk": 0.78, "xai_prediction_id": "pred-abc123"}
    # or   {"deal_id": 42, "days_in_stage": 17, "stage": "proposal"}

    summary         = models.TextField(blank=True, default="")   # human-readable one-liner
    resolved        = models.BooleanField(default=False)
    resolved_at     = models.DateTimeField(null=True, blank=True)

    fired_at        = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "rec_proactive_alerts"
        ordering = ["-fired_at"]
        indexes  = [
            models.Index(fields=["profile", "resolved"]),
            models.Index(fields=["trigger_type", "fired_at"]),
            models.Index(fields=["severity"]),
        ]

    def __str__(self):
        return f"[{self.severity.upper()}] {self.trigger_type} → {self.profile.subject_name}"