# Generated by Django 6.0.4 on 2026-05-24 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('partner', 'Partner'), ('prospect', 'Prospect')], default='prospect', max_length=20)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('at-risk', 'At Risk'), ('new', 'New'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('branches', models.JSONField(blank=True, default=list)),
                ('number_of_employees', models.IntegerField(default=0)),
                ('annual_revenue', models.BigIntegerField(default=0)),
                ('total_revenue', models.BigIntegerField(default=0)),
                ('account_owner', models.CharField(blank=True, max_length=255)),
                ('account_owner_avatar', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=3)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
