# Generated by Django 6.0.4 on 2026-05-17 15:03

import crmapp.agentic.agents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentic_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.agents.models.make_tool_id, max_length=50, primary_key=True, serialize=False)),
                ('tool_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🔧', max_length=10)),
                ('category', models.CharField(choices=[('Research', 'Research'), ('Communication', 'Communication'), ('CRM', 'CRM'), ('Productivity', 'Productivity'), ('Data', 'Data')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_key', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_tools',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.agents.models.make_config_id, max_length=50, primary_key=True, serialize=False)),
                ('llm', models.CharField(choices=[('groq/llama-3.3-70b-versatile', 'Llama 3.3 70B'), ('groq/llama-3.1-8b-instant', 'Llama 3.1 8B'), ('groq/mixtral-8x7b-32768', 'Mixtral 8x7B'), ('groq/gemma2-9b-it', 'Gemma 2 9B')], default='groq/llama-3.3-70b-versatile', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=1024)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('dept', models.CharField(default='General', max_length=100)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='agentic_core.resource')),
            ],
            options={
                'db_table': 'agent_configs',
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.agents.models.make_exec_id, max_length=50, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=300)),
                ('task_input', models.TextField(blank=True, default='')),
                ('dept', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('result', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agentic_core.resource')),
            ],
            options={
                'db_table': 'agent_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.agents.models.make_mem_id, max_length=50, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('episodic', 'Episodic')], default='short_term', max_length=20)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('importance', models.FloatField(default=0.5)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agentic_core.resource')),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-importance', '-created_at'],
                'unique_together': {('resource', 'key')},
            },
        ),
    ]
