# Generated by Django 6.0.4 on 2026-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='goal_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
