# Generated by Django 5.2.14 on 2026-05-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Office', 'Office'), ('Vehicle', 'Vehicle'), ('Machinery', 'Machinery'), ('License', 'License')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('disposed', 'Disposed')], default='available', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Preventive', 'Preventive'), ('Repair', 'Repair')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performed_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('next_due', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='assets.asset')),
            ],
        ),
    ]
