# Generated by Django 5.2.15 on 2026-06-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_link_assignment_to_hrm_employee'),
        ('crmapp', '0008_alter_bankdetails_id_alter_crmfile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='crmapp.employee'),
            preserve_default=False,
        ),
    ]
