# Generated by Django 5.2.15 on 2026-06-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetassignment_employee'),
        ('crmapp', '0008_alter_bankdetails_id_alter_crmfile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='crmapp.employee'),
        ),
    ]
