# Generated by Django 6.0.4 on 2026-05-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_companies', '0001_initial'),
        ('crm_contacts', '0002_contact_company_name_alter_contact_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('probability', models.IntegerField(default=50)),
                ('score', models.IntegerField(default=0)),
                ('deal_stage', models.CharField(choices=[('Lead', 'Lead'), ('Prospecting', 'Prospecting'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Lead', max_length=50)),
                ('status', models.CharField(choices=[('not-contacted', 'Not Contacted'), ('contacted', 'Contacted'), ('closed', 'Closed Won'), ('lost', 'Closed Lost')], default='not-contacted', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('LinkedIn', 'LinkedIn'), ('Event', 'Event'), ('Other', 'Other')], default='Website', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('last_contact', models.CharField(blank=True, default='Never', max_length=100)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('notes_count', models.IntegerField(default=0)),
                ('activities', models.IntegerField(default=0)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('activity_log', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm_companies.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm_contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_by', models.CharField(default='User', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='crm_leads.lead')),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
