# Generated by Django 6.0.4 on 2026-05-15 11:11

import crmapp.agentic.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(default=crmapp.agentic.core.models.make_res_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('AI Agent', 'AI Agent'), ('System', 'System'), ('Human', 'Human')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('busy', 'Busy'), ('idle', 'Idle'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('load_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capacity', models.IntegerField(default=100)),
                ('color', models.CharField(default='#3a9aab', max_length=7)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('role', models.TextField(blank=True, default='')),
                ('goal', models.TextField(blank=True, default='')),
                ('backstory', models.TextField(blank=True, default='')),
                ('tools', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
