# Generated by Django 6.0.4 on 2026-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='current_load',
            field=models.IntegerField(default=0),
        ),
    ]
