# Generated by Django 6.0.4 on 2026-06-25 15:54

import crmapp.ai.recommendation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_abtest_id, max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('control_label', models.CharField(default='Control', max_length=100)),
                ('treatment_label', models.CharField(default='Treatment', max_length=100)),
                ('primary_metric', models.CharField(choices=[('ctr', 'Click-Through Rate'), ('conv', 'Conversion Rate'), ('revenue', 'Revenue'), ('trust', 'Trust Score'), ('open_rate', 'Open Rate')], default='ctr', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('winner', models.CharField(blank=True, default='', max_length=100)),
                ('lift', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rec_ab_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_alert_id, max_length=60, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('emotion_angry', 'Angry Email Detected'), ('emotion_fearful', 'Fearful Email Detected'), ('churn_risk_high', 'High Churn Risk (XAI)'), ('conversion_drop', 'Conversion Probability Dropped'), ('deal_stalled', 'Deal Stalled in Stage'), ('lead_no_contact', 'Lead Not Contacted'), ('contract_expiring', 'Contract Expiring Soon'), ('similar_lead_closed', 'Similar Lead Just Closed')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('signal_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rec_proactive_alerts',
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPerformance',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_channel_id, max_length=60, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('email', 'Email'), ('push', 'Push'), ('in_app', 'In-App')], max_length=20)),
                ('date', models.DateField()),
                ('recs_delivered', models.IntegerField(default=0)),
                ('recs_clicked', models.IntegerField(default=0)),
                ('recs_converted', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('conv_rate', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'rec_channel_performance',
                'ordering': ['-date', 'channel'],
                'unique_together': {('channel', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_mperf_id, max_length=60, primary_key=True, serialize=False)),
                ('model_name', models.CharField(choices=[('hybrid', 'Hybrid'), ('collab', 'Collaborative Filtering'), ('content', 'Content-Based'), ('context', 'Context-Aware')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('recs_total', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('conv_rate', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rec_model_performance',
                'ordering': ['-year', '-month', 'model_name'],
                'unique_together': {('model_name', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_profile_id, max_length=60, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact')], max_length=20)),
                ('subject_id', models.CharField(max_length=100)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject_email', models.EmailField(blank=True, default='', max_length=254)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('churn_risk_score', models.FloatField(default=0.0)),
                ('ltv_estimate', models.FloatField(default=0.0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('segment', models.CharField(choices=[('high_value', 'High-Value'), ('loyal', 'Loyal'), ('at_risk', 'At-Risk'), ('new', 'New'), ('occasional', 'Occasional')], default='new', max_length=20)),
                ('top_category', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('email', 'Email'), ('push', 'Push')], default='email', max_length=20)),
                ('last_emotion', models.CharField(blank=True, default='', max_length=20)),
                ('last_emotion_score', models.FloatField(blank=True, null=True)),
                ('xai_conversion_prob', models.FloatField(blank=True, null=True)),
                ('xai_deal_win_prob', models.FloatField(blank=True, null=True)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rec_user_profiles',
                'ordering': ['-engagement_score'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='rec_user_pr_subject_5631fc_idx'), models.Index(fields=['segment'], name='rec_user_pr_segment_a07754_idx'), models.Index(fields=['churn_risk_score'], name='rec_user_pr_churn_r_13327d_idx')],
                'unique_together': {('subject_type', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_rec_id, max_length=60, primary_key=True, serialize=False)),
                ('rec_type', models.CharField(choices=[('upsell', 'Upsell'), ('cross_sell', 'Cross-Sell'), ('retention', 'Retention'), ('re_engage', 'Re-Engage'), ('top_n', 'Top-N'), ('next_action', 'Next Best Action')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('revenue_impact', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('model_used', models.CharField(choices=[('hybrid', 'Hybrid'), ('collab', 'Collaborative Filtering'), ('content', 'Content-Based'), ('context', 'Context-Aware'), ('proactive', 'Proactive (Signal-Driven)')], default='hybrid', max_length=20)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('email', 'Email'), ('push', 'Push'), ('in_app', 'In-App')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('clicked', 'Clicked'), ('converted', 'Converted'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('trigger_signals', models.JSONField(blank=True, default=dict)),
                ('is_proactive', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proactive_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='ai_recommendation.proactivealert')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_recommendation.userprofile')),
            ],
            options={
                'db_table': 'rec_recommendations',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='proactivealert',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_alerts', to='ai_recommendation.userprofile'),
        ),
        migrations.CreateModel(
            name='FeedbackEvent',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_feedback_id, max_length=60, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('clicked', 'Clicked'), ('converted', 'Converted / Purchased'), ('ignored', 'Ignored'), ('dismissed', 'Dismissed'), ('rated_up', 'Rated Up'), ('rated_down', 'Rated Down'), ('unsubscribed', 'Unsubscribed'), ('opened', 'Opened')], max_length=20)),
                ('signal_type', models.CharField(choices=[('explicit', 'Explicit'), ('implicit', 'Implicit')], max_length=10)),
                ('weight', models.FloatField(default=0.0)),
                ('revenue_realised', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='ai_recommendation.recommendationitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='ai_recommendation.userprofile')),
            ],
            options={
                'db_table': 'rec_feedback_events',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTestAssignment',
            fields=[
                ('id', models.CharField(default=crmapp.ai.recommendation.models.make_assign_id, max_length=60, primary_key=True, serialize=False)),
                ('variant', models.CharField(choices=[('control', 'Control'), ('treatment', 'Treatment')], max_length=20)),
                ('converted', models.BooleanField(default=False)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ai_recommendation.abtest')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_assignments', to='ai_recommendation.recommendationitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_assignments', to='ai_recommendation.userprofile')),
            ],
            options={
                'db_table': 'rec_ab_test_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['profile', 'status'], name='rec_recomme_profile_62ac93_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['status', 'created_at'], name='rec_recomme_status_9c503e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['is_proactive'], name='rec_recomme_is_proa_e1a393_idx'),
        ),
        migrations.AddIndex(
            model_name='proactivealert',
            index=models.Index(fields=['profile', 'resolved'], name='rec_proacti_profile_159bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='proactivealert',
            index=models.Index(fields=['trigger_type', 'fired_at'], name='rec_proacti_trigger_1d8440_idx'),
        ),
        migrations.AddIndex(
            model_name='proactivealert',
            index=models.Index(fields=['severity'], name='rec_proacti_severit_a84340_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackevent',
            index=models.Index(fields=['profile', 'recorded_at'], name='rec_feedbac_profile_816145_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackevent',
            index=models.Index(fields=['action'], name='rec_feedbac_action_c169fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='abtestassignment',
            unique_together={('test', 'profile')},
        ),
    ]
